// data.js — the master list of vegetables, fruits, and other plants to track.
// Add or remove items here to customise what shows up in the tracker.

const VEGETABLES = [
  { name: "Artichoke", cat: "Vegetables", emoji: "🌿" },
  { name: "Asparagus", cat: "Vegetables", emoji: "🌿" },
  { name: "Aubergine", cat: "Vegetables", emoji: "🍆" },
  { name: "Beetroot", cat: "Root veg", emoji: "🟣" },
  { name: "Broad beans", cat: "Legumes", emoji: "🫘" },
  { name: "Broccoli", cat: "Brassicas", emoji: "🥦" },
  { name: "Brussels sprouts", cat: "Brassicas", emoji: "🥦" },
  { name: "Butternut squash", cat: "Squash", emoji: "🎃" },
  { name: "Cabbage", cat: "Brassicas", emoji: "🥬" },
  { name: "Carrot", cat: "Root veg", emoji: "🥕" },
  { name: "Cauliflower", cat: "Brassicas", emoji: "🥦" },
  { name: "Celeriac", cat: "Root veg", emoji: "🌿" },
  { name: "Celery", cat: "Vegetables", emoji: "🌿" },
  { name: "Chard", cat: "Leafy greens", emoji: "🥬" },
  { name: "Chicory", cat: "Leafy greens", emoji: "🌿" },
  { name: "Courgette", cat: "Squash", emoji: "🥒" },
  { name: "Cucumber", cat: "Squash", emoji: "🥒" },
  { name: "Edamame", cat: "Legumes", emoji: "🫘" },
  { name: "Fennel", cat: "Vegetables", emoji: "🌿" },
  { name: "French beans", cat: "Legumes", emoji: "🫘" },
  { name: "Garlic", cat: "Alliums", emoji: "🧄" },
  { name: "Jerusalem artichoke", cat: "Root veg", emoji: "🌿" },
  { name: "Kale", cat: "Brassicas", emoji: "🥬" },
  { name: "Leek", cat: "Alliums", emoji: "🌿" },
  { name: "Lettuce", cat: "Leafy greens", emoji: "🥬" },
  { name: "Mangetout", cat: "Legumes", emoji: "🫘" },
  { name: "Mushroom", cat: "Fungi", emoji: "🍄" },
  { name: "Onion", cat: "Alliums", emoji: "🧅" },
  { name: "Pak choi", cat: "Brassicas", emoji: "🥬" },
  { name: "Parsnip", cat: "Root veg", emoji: "🌿" },
  { name: "Peas", cat: "Legumes", emoji: "🫛" },
  { name: "Pepper", cat: "Vegetables", emoji: "🌶️" },
  { name: "Potato", cat: "Root veg", emoji: "🥔" },
  { name: "Pumpkin", cat: "Squash", emoji: "🎃" },
  { name: "Purple sprouting broccoli", cat: "Brassicas", emoji: "🥦" },
  { name: "Radish", cat: "Root veg", emoji: "🌿" },
  { name: "Runner beans", cat: "Legumes", emoji: "🫘" },
  { name: "Shallot", cat: "Alliums", emoji: "🧅" },
  { name: "Spinach", cat: "Leafy greens", emoji: "🥬" },
  { name: "Spring onion", cat: "Alliums", emoji: "🌿" },
  { name: "Swede", cat: "Root veg", emoji: "🌿" },
  { name: "Sweetcorn", cat: "Vegetables", emoji: "🌽" },
  { name: "Sweet potato", cat: "Root veg", emoji: "🍠" },
  { name: "Tomato", cat: "Vegetables", emoji: "🍅" },
  { name: "Turnip", cat: "Root veg", emoji: "🌿" },
  { name: "Watercress", cat: "Leafy greens", emoji: "🌿" },
  { name: "Apple", cat: "Fruits", emoji: "🍎" },
  { name: "Apricot", cat: "Fruits", emoji: "🍑" },
  { name: "Avocado", cat: "Fruits", emoji: "🥑" },
  { name: "Banana", cat: "Fruits", emoji: "🍌" },
  { name: "Blackberry", cat: "Berries", emoji: "🫐" },
  { name: "Blackcurrant", cat: "Berries", emoji: "🫐" },
  { name: "Blueberry", cat: "Berries", emoji: "🫐" },
  { name: "Cherry", cat: "Fruits", emoji: "🍒" },
  { name: "Clementine", cat: "Citrus", emoji: "🍊" },
  { name: "Cranberry", cat: "Berries", emoji: "🫐" },
  { name: "Date", cat: "Fruits", emoji: "🌿" },
  { name: "Fig", cat: "Fruits", emoji: "🫐" },
  { name: "Grape", cat: "Fruits", emoji: "🍇" },
  { name: "Grapefruit", cat: "Citrus", emoji: "🍊" },
  { name: "Kiwi", cat: "Fruits", emoji: "🥝" },
  { name: "Lemon", cat: "Citrus", emoji: "🍋" },
  { name: "Lime", cat: "Citrus", emoji: "🍋" },
  { name: "Mango", cat: "Tropical", emoji: "🥭" },
  { name: "Melon", cat: "Fruits", emoji: "🍈" },
  { name: "Nectarine", cat: "Fruits", emoji: "🍑" },
  { name: "Orange", cat: "Citrus", emoji: "🍊" },
  { name: "Papaya", cat: "Tropical", emoji: "🌿" },
  { name: "Passion fruit", cat: "Tropical", emoji: "🌿" },
  { name: "Peach", cat: "Fruits", emoji: "🍑" },
  { name: "Pear", cat: "Fruits", emoji: "🍐" },
  { name: "Pineapple", cat: "Tropical", emoji: "🍍" },
  { name: "Plum", cat: "Fruits", emoji: "🫐" },
  { name: "Pomegranate", cat: "Fruits", emoji: "🌿" },
  { name: "Raspberry", cat: "Berries", emoji: "🫐" },
  { name: "Rhubarb", cat: "Fruits", emoji: "🌿" },
  { name: "Strawberry", cat: "Berries", emoji: "🍓" },
  { name: "Watermelon", cat: "Fruits", emoji: "🍉" }
];
